[tools]
terraform = '1.5.3'
terraform-docs = '0.16.0'
direnv = '2.32.2'
terraform-ls = '0.30.3'
task = '3.23.0'
pre-commit = '3.3.3'
python = '3.11.4'
shfmt = '3.7.0'
shellcheck = '0.9.0'

[plugins]
terraform = 'https://github.com/asdf-community/asdf-hashicorp'
terraform-docs = 'https://github.com/looztra/asdf-terraform-docs'
terraform-ls = 'https://github.com/asdf-community/asdf-hashicorp'
direnv = 'https://github.com/asdf-community/asdf-direnv'
task = 'https://github.com/particledecay/asdf-task'
shellcheck = 'https://github.com/luizm/asdf-shellcheck'
python = 'https://github.com/rtx-plugins/rtx-python'
shfmt = 'https://github.com/luizm/asdf-shfmt'
pre-commit = 'https://github.com/jonathanmorley/asdf-pre-commit'

[settings] # project-local settings
verbose = true
