name: Create release when tag is pushed

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: ncipollo/release-action@a2e71bdd4e7dab70ca26a852f29600c98b33153e # v1
        with:
          generateReleaseNotes: true
          name: '${{ github.ref_name }}'
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}