name: Create release when tag is pushed

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: ncipollo/release-action@6c75be85e571768fa31b40abf38de58ba0397db5 # v1
        with:
          generateReleaseNotes: true
          name: '${{ github.ref_name }}'
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}